name: trafalgar
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - jupyter
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - tabulate
  - plotly
  - statsmodels
  - pip
  - pip:
    - yfinance
    - pandas_datareader